---
# Copyright 2014, Rackspace US, Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

- name: Install pip packages (venv)
  pip:
    name: "{{ item }}"
    state: latest
    extra_args: "{{ pip_install_options | default('') }}"
    virtualenv: "{{ horizon_venv_bin | dirname }}"
    virtualenv_site_packages: "no"
  register: install_pip_packages
  until: install_pip_packages|success
  retries: 5
  delay: 2
  with_items: "{{ stashboard_pip_packages }}"
  when:
    horizon_venv_enabled | bool
  tags:
    - stashboard-install
    - stashboard-pip-packages

- name: Generate Horizon panel group
  template:
    src: _1710_database_panel_group.py
    dest: "{{ horizon_lib_dir }}/openstack_dashboard/local/enabled/_1710_database_panel_group.py"
    mode: "0644"
    owner: root
    group: root
  notify: Restart apache2

- name: Generate Horizon database panel
  template:
    src: _1720_project_databases_panel.py
    dest: "{{ horizon_lib_dir }}/openstack_dashboard/local/enabled/_1720_project_databases_panel.py"
    mode: "0644"
    owner: root
    group: root
  notify: Restart apache2

- name: Generate Horizon cluster panel
  template:
    src: _1740_project_databases_clusters_panel.py
    dest: "{{ horizon_lib_dir }}/openstack_dashboard/local/enabled/_1740_project_databases_clusters_panel.py"
    mode: "0644"
    owner: root
    group: root
  notify: Restart apache2

- name: Collect and compress static files
  command: "{{ item }}"
  become: true
  become_user: "{{ horizon_system_user_name }}"
  with_items:
    - "{{ horizon_venv_bin }}/horizon-manage.py collectstatic --noinput"
    - "{{ horizon_venv_bin }}/horizon-manage.py compress --force"
  notify: Restart apache2
